data_root: data

data_ingestion:
  root_dir: data/data_ingestion
  download_url: https://github.com/entbappy/Branching-tutorial/raw/master/cat-dog-data.zip
  local_data_file: data/data_ingestion/raw_data.zip
  unzip_dir: data/data_ingestion

prepare_base_model:
  root_dir: data/prepare_base_model
  base_model_path: data/prepare_base_model/base_model.keras
  updated_base_model_path: data/prepare_base_model/updated_base_model.keras

save_callbacks:
  root_dir: data/prepare_callbacks
  tensorboard_root_log_dir: data/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: data/prepare_callbacks/checkpoint_dir/model.keras


training:
  root_dir: data/training
  trained_model_path: data/training/model.keras



